apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-backend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: learner-backend
  template:
    metadata:
      labels:
        app: learner-backend
    spec:
      containers:
        - name: learner-backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: {{ .Values.backend.containerPort }}
          env:
            - name: DB_URI
              value: {{ .Values.backend.mongoUri | quote }}
