apiVersion: v1
kind: Service
metadata:
  name: learner-backend
  labels:
    app: learner-backend
    app.kubernetes.io/managed-by: "Helm"
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: learner-backend
  ports:
    - port: {{ .Values.backend.containerPort }}
      targetPort: {{ .Values.backend.containerPort }}
