apiVersion: v1
kind: Service
metadata:
  name: learner-frontend
spec:
  type: NodePort
  selector:
    app: learner-frontend
  ports:
    - port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.nodePort }}
