apiVersion: v1
kind: Service
metadata:
  name: learner-frontend
spec:
  selector:
    app: learner-frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.containerPort }}
      targetPort: {{ .Values.frontend.containerPort }}
      nodePort: {{ .Values.frontend.nodePort }}
