apiVersion: apps/v1
kind: Deployment
metadata:
  name: learner-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: learner-frontend
  template:
    metadata:
      labels:
        app: learner-frontend
    spec:
      containers:
        - name: learner-frontend
          image: {{ .Values.frontend.image }}
          ports:
            - containerPort: {{ .Values.frontend.containerPort }}
