apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}-service
  labels:
    app: {{ .Values.frontend.name }}
    chart: {{ include "mern-chart.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.frontend.name }}
    release: {{ .Release.Name }}
