apiVersion: v1
kind: Service
metadata:
  name: learner-frontend
spec:
  selector:
    app: learner-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort  # You can change to LoadBalancer on cloud (e.g., EKS)
