apiVersion: v2
name: mern-chart
description: A Helm chart for MERN Stack Application
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mern
  - mongodb
  - express
  - react
  - nodejs
maintainers:
  - name: DevOps Team
    email: devops@example.com
