backend:
  name: learner-backend
  image: xxradeonxfs/learner-backend:latest
  replicas: 2
  port: 3000
  service:
    type: ClusterIP
    port: 3000
    targetPort: 3000
  env:
    - name: NODE_ENV
      value: "production"
    - name: MONGODB_URI
      value: "mongodb://mongodb-service.database.svc.cluster.local:27017/learnerdb"

frontend:
  name: learner-frontend
  image: xxradeonxfs/learner-frontend:latest
  replicas: 2
  port: 3000
  service:
    type: LoadBalancer
    port: 80
    targetPort: 3000
  env:
    - name: REACT_APP_API_URL
      value: "http://learner-backend-service:3000"
